import { requestBgmPlay } from './bgm-consent.js';
// New presentation over the existing public modules. Keep all data/owner hooks.
document.body.classList.add('sketch-site');
const oldContent=document.querySelector('.rv-shell-content')||document.querySelector('td.content');
const main=document.createElement('main');main.className='sketch-content';main.id='sketch-content';
if(oldContent){while(oldContent.firstChild)main.append(oldContent.firstChild);document.body.append(main)}
const header=document.createElement('header');header.className='sketch-header';header.innerHTML='<a class="sketch-brand" href="/">콜드워터킴</a><nav aria-label="공통 메뉴"><a href="/">홈</a><a href="/#home">전체 보기</a><a href="/album/">앨범</a></nav>';document.body.prepend(header);
const svg=(file,b,label)=>`<svg viewBox="${b.join(' ')}" role="img" aria-label="${label}"><defs><clipPath id="sk-${label.replace(/\s/g,'')}"><rect x="${b[0]}" y="${b[1]}" width="${b[2]}" height="${b[3]}"/></clipPath></defs><image clip-path="url(#sk-${label.replace(/\s/g,'')})" href="/assets/sketch/${file}.png" width="${file==='original'?1333:1024}" height="${file==='original'?1888:1536}" preserveAspectRatio="none"/></svg>`;
const isRoot=!!document.querySelector('#records-app')&&['/','/index.html'].includes(location.pathname);
let home;
if(isRoot){home=document.createElement('section');home.id='sketch-home';home.setAttribute('aria-label','탐색 방향 선택');home.innerHTML=`<nav class="sk-home-nav" aria-label="탐색 방향"><div class="sk-primary"><a href="#posts" aria-label="나으 생각">${svg('original',[260,165,710,250],'나으 생각')}</a><a href="#daily" aria-label="나으 하루">${svg('original',[280,440,660,275],'나으 하루')}</a><div class="sk-pair"><a href="#projects" aria-label="내가 만든 것들">${svg('original',[285,780,310,225],'내가 만든 것들')}</a><a href="#nasajab" aria-label="나를 사로잡은 것들">${svg('original',[685,750,295,265],'나를 사로잡은 것들')}</a></div></div><div class="sk-secondary"><a href="/guestbook.html">방명록!</a><a href="/about.html">about me</a></div></nav><section class="sk-player" aria-label="음악 플레이어"><svg class="sk-player-frame" viewBox="130 1305 980 445" preserveAspectRatio="none" aria-hidden="true"><image href="/assets/sketch/original.png" width="1333" height="1888" preserveAspectRatio="none"/><path d="M205 1365H1040V1696H205Z" fill="white"/></svg><div class="sk-track" data-live-title>음악을 불러오는 중…</div><input type="range" class="sk-seek" aria-label="재생 위치" min="0" max="100" value="0" step="0.1"><span class="sk-time">0:00</span><div class="sk-controls"><button class="sk-play" aria-label="음악 재생">${svg('original',[480,1590,95,110],'재생')}</button><button class="sk-shuffle" aria-label="다음 곡 랜덤 재생">${svg('original',[590,1590,110,110],'셔플')}</button></div><p class="sk-player-error" role="status"></p></section>`;main.prepend(home)}
// Keep the original single audio element and playlist/consent events.
const audio=document.querySelector('[data-bgm]');
const dock=document.createElement('aside');dock.className='sk-music-dock';dock.setAttribute('aria-label','음악');dock.innerHTML='<button type="button" class="sk-dock-play" aria-label="음악 재생">♫ 재생</button><span class="sk-dock-title"></span><a href="/admin/login.html?next=/" class="sk-owner-link">OWNER</a>';document.body.append(dock);
const titleNode=home?.querySelector('[data-live-title]'),play=home?.querySelector('.sk-play'),playArt=play?.innerHTML,seek=home?.querySelector('.sk-seek');
async function toggle(){if(!audio)return;try{if(audio.paused)await requestBgmPlay(audio,true);else audio.pause()}catch{if(home)home.querySelector('.sk-player-error').textContent='재생하지 못했어. 다시 눌러줘.'}}
if(audio){if(play)play.onclick=toggle;dock.querySelector('button').onclick=toggle;home?.querySelector('.sk-shuffle').addEventListener('click',()=>document.querySelector('[data-bgm-shuffle]')?.click());
const update=()=>{const title=audio._bgmTrackTitle?.textContent||audio._bgmPlaylist?.[audio._bgmTrackIndex]?.title||'등록된 음악 없음';if(titleNode)titleNode.textContent=title;dock.querySelector('.sk-dock-title').textContent=title;dock.querySelector('button').textContent=audio.paused?'♫ 재생':'Ⅱ 정지';if(play){play.innerHTML=audio.paused?playArt:'<span aria-hidden="true">Ⅱ</span>';play.setAttribute('aria-label',audio.paused?'음악 재생':'음악 일시정지')}if(seek){seek.value=Number.isFinite(audio.duration)&&audio.duration?100*audio.currentTime/audio.duration:0;seek.disabled=!Number.isFinite(audio.duration);home.querySelector('.sk-time').textContent=Math.floor(audio.currentTime/60)+':'+String(Math.floor(audio.currentTime%60)).padStart(2,'0')}};
['play','pause','loadedmetadata','timeupdate','bgm-playlist-changed','emptied'].forEach(e=>audio.addEventListener(e,update));update();if(seek)seek.oninput=()=>{if(Number.isFinite(audio.duration))audio.currentTime=audio.duration*Number(seek.value)/100};
new MutationObserver(update).observe(audio.closest('.mini-player')||audio.parentElement,{childList:true,subtree:true,characterData:true});
}
function sync(){const onHome=isRoot&&(!location.hash||location.hash==='#start');document.body.classList.toggle('sketch-home-view',onHome);if(home)home.hidden=!onHome;const records=document.querySelector('#records-content');if(records)records.hidden=onHome;dock.hidden=onHome;document.querySelectorAll('.sketch-header nav a').forEach(a=>a.toggleAttribute('aria-current',a.href===location.href));if(onHome)window.scrollTo(0,0)}
window.addEventListener('hashchange',sync);sync();new ResizeObserver(()=>document.documentElement.style.setProperty('--sk-header-height',header.getBoundingClientRect().height+'px')).observe(header);

// Owner controls are the existing elements, never a second editor or audio player.
const legacyPlayer=audio?.closest('.mini-player');
if(legacyPlayer){let exposed=false;const expose=()=>{if(exposed||!legacyPlayer.querySelector('.bgm-owner-row'))return;exposed=true;const controls=document.createElement('details');controls.className='sk-owner-music';controls.innerHTML='<summary>음악 관리</summary>';dock.append(controls);controls.append(legacyPlayer)};new MutationObserver(expose).observe(legacyPlayer,{childList:true});expose()}
