-- 1. Site Settings 테이블 생성
create table if not exists site_settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- RLS 활성화
alter table site_settings enable row level security;
alter table posts enable row level security;
-- 2. RLS 정책 (Posts & Site Settings)
-- [Posts] 누구나 조회 가능
create policy "Public posts are viewable by everyone." on posts for
select using (true);
-- [Posts] 관리자만 작성/수정/삭제 (기존 정책이 있다면 삭제 후 재생성 권장)
create policy "Admin can insert posts" on posts for
insert with check (auth.role() = 'authenticated');
create policy "Admin can update posts" on posts for
update using (auth.role() = 'authenticated');
create policy "Admin can delete posts" on posts for delete using (auth.role() = 'authenticated');
-- [Site Settings] 누구나 조회 가능
create policy "Public settings are viewable by everyone." on site_settings for
select using (true);
-- [Site Settings] 관리자만 작성/수정/삭제
create policy "Admin can manage site settings" on site_settings for all using (auth.role() = 'authenticated');